# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_rename_produtoid_itempedido_codproduto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'item do pedido', 'verbose_name_plural': 'itens do pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
