# Generated by Django 4.1.6 on 2023-02-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_endereco_nome_do_logradouro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='Numero',
            field=models.CharField(default='', help_text='Numero da Residencia', max_length=7, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
