# Generated by Django 4.1.6 on 2023-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0004_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='Complem',
            field=models.CharField(default='', help_text='Complemento Casa ou Apptamento', max_length=7, verbose_name='Complemento'),
            preserve_default=False,
        ),
    ]
