# Generated by Django 4.1.6 on 2023-02-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0007_endereco_cidade_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='Estado',
            field=models.CharField(
                choices=[
                    ('AC', 'AC'),
                    ('AP', 'AM'),
                    ('AM', 'AM'),
                    ('BA', 'BA'),
                    ('CE', 'CE'),
                    ('DF', 'DF'),
                    ('ES', 'ES'),
                    ('GO', 'GO'),
                    ('MA', 'MA'),
                    ('MT', 'MT'),
                    ('MS', 'MS'),
                    ('MG', 'MG'),
                    ('PA', 'PA'),
                    ('PB', 'PB'),
                    ('PR', 'PR'),
                    ('PE', 'PE'),
                    ('PI', 'PI'),
                    ('RJ', 'RJ'),
                    ('RN', 'RN'),
                    ('RS', 'RS'),
                    ('RO', 'RO'),
                    ('RR', 'RR'),
                    ('SC', 'SC'),
                    ('SP', 'SP'),
                    ('SE', 'SE'),
                    ('TO', 'TO'),
                ],
                default='CE',
                help_text='Nome do Estado',
                max_length=9,
                verbose_name='Estado',
            ),
        ),
    ]
