# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
    ]
