# Generated by Django 4.1.6 on 2023-02-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0008_alter_endereco_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
