# Generated by Django 4.1.6 on 2023-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_delete_sexo_cliente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(default='N', max_length=80),
        ),
    ]
