# Generated by Django 4.1.6 on 2023-02-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'cliente',
            '0006_remove_cliente_numerowhatazapp_remove_cliente_dd_and_more',
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='numeroCPF',
            new_name='CPF',
        ),
    ]
