# Generated by Django 4.1.6 on 2023-02-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=80)),
                ('quantidade', models.FloatField(default=0)),
                (
                    'categoria',
                    models.ForeignKey(
                        null='true',
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='produto.categoria',
                    ),
                ),
            ],
        ),
    ]
