# Generated by Django 4.1.6 on 2023-02-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_categoria_titulo_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.FloatField(default=0, help_text='Quantidade produto, Sem traços ou pontos', verbose_name='Quantidade do produto'),
        ),
    ]
