# Generated by Django 4.1.6 on 2023-02-24 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('documentos_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosrh',
            name='descricao',
            field=models.CharField(default='', help_text='Nome do documento completo', max_length=100, verbose_name='Nome do documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentosrh',
            name='pertence',
            field=models.ForeignKey(blank=True, help_text='Nome do documento completo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario'),
        ),
    ]
