# Generated by Django 4.1.6 on 2023-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosrh',
            name='descricao',
            field=models.CharField(default='', help_text='Nome do documento completo', max_length=100, verbose_name='Nome do documento'),
            preserve_default=False,
        ),
    ]
