# Generated by Django 4.1.6 on 2023-02-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_rh', '0002_documentosrh_descricao_documentosrh_pertence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosrh',
            name='pertence',
        ),
    ]
