# Generated by Django 4.1.6 on 2023-02-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcioanrio',
            name='Cpf',
            field=models.CharField(default='', help_text='Número do CPF, Sem traços ou pontos', max_length=15, verbose_name='Número do CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='celular',
            field=models.CharField(blank=True, help_text='Número do celular com o DDD Sem traços ou parentes', max_length=11, null=True, verbose_name='Numero de celular com o (DDD)'),
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='datanascimento',
            field=models.DateField(blank=True, help_text='Data de Nascimento do cliente', null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='email',
            field=models.EmailField(default='', help_text='Digite o E-mail válido', max_length=50, verbose_name='E-mail de Contato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='fixo',
            field=models.CharField(default='', help_text='Número Fixo apenas número Sem traços ou parentes', max_length=12, verbose_name='Numero de fixo com o (DDD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='nome',
            field=models.CharField(default='', help_text='Nome Completo do Cliente', max_length=80, verbose_name='Nome do cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='profissao',
            field=models.CharField(blank=True, help_text='Profissão Auto Declarada do Cliente', max_length=80, null=True, verbose_name='Profissão do Cliente'),
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='rg',
            field=models.CharField(default='', help_text='RG Sem traços ou pontos', max_length=15, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='M', help_text='Escolha umas das opções', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='situacao',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', help_text='Escolha entre Ativo ou Inativo', max_length=1, verbose_name='Situação do cliente'),
        ),
        migrations.AddField(
            model_name='funcioanrio',
            name='what',
            field=models.CharField(blank=True, help_text='Número de contato para o Whatzapp', max_length=11, null=True, verbose_name='Contato do Whatzapp'),
        ),
    ]
