# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentosrh',
            options={'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
        migrations.AlterModelOptions(
            name='horaextra_funcionario',
            options={'verbose_name': 'hora extra', 'verbose_name_plural': 'horas extra'},
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='horaextra_funcionario',
            old_name='Logradouro',
            new_name='logradouro',
        ),
    ]
