# Generated by Django 4.1.7 on 2023-03-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_documentosrh_options_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoraExtra_Funcionario',
            new_name='HoraExtraFuncionario',
        ),
    ]
