# Generated by Django 4.1.7 on 2023-03-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_rename_horaextra_funcionario_horaextrafuncionario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentosrh',
            new_name='Documento',
        ),
    ]
