# Generated by Django 4.1.6 on 2023-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horaextrar_rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra_funcionario',
            name='motivo',
            field=models.CharField(default='', help_text='Nome do Motivo Hora extrar', max_length=100, verbose_name='Motivo Hora Extra'),
            preserve_default=False,
        ),
    ]
