# Generated by Django 4.1.6 on 2023-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_sexo_remove_cliente_numerocnpj_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(
                choices=[
                    ('M', 'Masculino'),
                    ('F', 'Feminino'),
                    ('O', 'Outros'),
                ],
                default='N',
                max_length=1,
            ),
        ),
    ]
