# Generated by Django 4.1.6 on 2023-02-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_alter_cliente_cpf_alter_cliente_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='Cpf',
        ),
    ]
