# Generated by Django 4.1.7 on 2023-03-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_rename_cpf_cliente_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
    ]
