# Generated by Django 4.1.6 on 2023-02-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_statuspedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itempedido',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('pedido', models.CharField(max_length=255)),
                ('nomeproduto', models.CharField(max_length=255)),
                ('produtoID', models.PositiveIntegerField()),
                ('preco_produto', models.FloatField()),
                ('quantidade_Material', models.PositiveIntegerField()),
                ('imagem', models.CharField(max_length=2000)),
            ],
        ),
    ]
