# Generated by Django 4.1.6 on 2023-02-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_rename_numeropedido_itempedido_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='produtoID',
            new_name='codproduto',
        ),
    ]
